apiVersion: batch/v1
kind: Job
metadata:
  name: cds-deploy-job
  annotations:
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: cds-deploy
          image: harrazrajang/sap-cap:1.0
          command:
            - "sh"
            - "-c"
            - "sleep 60 && cds deploy"
          env:
            - name: OPA_URL
              value: "http://opa:8181"
            - name: DB_HOST
              value: "postgres"
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: "bookshop-tia"
            - name: DB_USER
              value: "postgres"
            - name: DB_PASSWORD
              value: "postgres"
