# Values for the SAP CAP application
replicaCount: 1

image:
  repository: "harrazrajang/sap-cap:1.1"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 4004

environment:
  OPA_HOST: "opa"
  OPA_PORT: "8181"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "bookshop-tia"
  DB_USER: "postgres"
  DB_PASSWORD: "postgres"
# Values for the OPA
